In [1]:
import numpy as np
import pandas as pd
from simulator import simulator
from ads import ADS

In [4]:
accident_prob =   pd.read_csv("data/accident_prob_bis", index_col=0, delim_whitespace=True)
inj_fat_out   =   pd.read_csv("data/inj_fat_prob_out_bis", index_col=0, delim_whitespace=True)
inj_fat_in    =   pd.read_csv("data/inj_fat_prob_in_bis", index_col=0, delim_whitespace=True)

#inj_fat_in  = [x.drop(columns="type").values for _, x in inj_fat_in.groupby(inj_fat_in['type']) ]
#inj_fat_out = [x.drop(columns="type").values for _, x in inj_fat_out.groupby(inj_fat_out['type']) ]

In [10]:
print(inj_fat_in.to_latex())

\begin{tabular}{lrrrrr}
\toprule
{} &  type &  0 &      1 &      2 &      3 \\
idx &       &    &        &        &        \\
\midrule
0   &     0 &  1 &  0.980 &  0.973 &  0.950 \\
1   &     0 &  0 &  0.012 &  0.019 &  0.045 \\
2   &     0 &  0 &  0.008 &  0.008 &  0.005 \\
0   &     1 &  1 &  0.985 &  0.980 &  0.952 \\
1   &     1 &  0 &  0.009 &  0.012 &  0.036 \\
2   &     1 &  0 &  0.006 &  0.008 &  0.012 \\
0   &     2 &  1 &  1.000 &  1.000 &  1.000 \\
1   &     2 &  0 &  0.000 &  0.000 &  0.000 \\
2   &     2 &  0 &  0.000 &  0.000 &  0.000 \\
0   &     3 &  1 &  0.978 &  0.967 &  0.934 \\
1   &     3 &  0 &  0.013 &  0.022 &  0.053 \\
2   &     3 &  0 &  0.009 &  0.011 &  0.013 \\
0   &     4 &  1 &  0.980 &  0.973 &  0.950 \\
1   &     4 &  0 &  0.012 &  0.019 &  0.045 \\
2   &     4 &  0 &  0.008 &  0.008 &  0.005 \\
0   &     5 &  1 &  1.000 &  1.000 &  1.000 \\
1   &     5 &  0 &  0.000 &  0.000 &  0.000 \\
2   &     5 &  0 &  0.000 &  0.000 &  0.000 \\
\bottomrule
\end{ta

In [15]:
ut_out = []
ut_in = []

for i in range(1):
    print(i)
    l = 1000
    w = [0.2, 0.0, 0.8]
    sim = simulator(l)
    env = sim.simulate_environment()
    ads =  ADS(env, accident_prob, inj_fat_in, inj_fat_out, w)
    ads.complete_road()
    ut_out.append(ads.ut_out.mean())
    ut_in.append(ads.ut_in.mean())

0


In [18]:
ads.ut_in.mean()

-0.18

In [17]:
np.unique(ads.acc_type, return_counts=True)

(array([0., 1., 2., 4., 5.]), array([ 14,  15,  19,   3, 949]))

In [7]:
ut_out = []
ut_in = []

for i in range(10):
    print(i)
    l = 1000
    w = [0.2, 0.0, 0.8]
    sim = simulator(l)
    env = sim.simulate_environment()
    ads =  ADS(env, accident_prob, inj_fat_in, inj_fat_out, w)
    ads.complete_road()
    ut_out.append(ads.ut_out.mean())
    ut_in.append(ads.ut_in.mean())

0
1
2
3
4
5
6
7
8
9


In [8]:
ut_out_prev = []
ut_in_prev = []

for i in range(10):
    print(i)
    l = 1000
    w = [0.2, 0.8, 0.0]
    sim = simulator(l)
    env = sim.simulate_environment()
    ads =  ADS(env, accident_prob, inj_fat_in, inj_fat_out, w)
    ads.complete_road()
    ut_out_prev.append(ads.ut_out.mean())
    ut_in_prev.append(ads.ut_in.mean())

0
1
2
3
4
5
6
7
8
9


In [9]:
np.mean( np.array(ut_out))

-0.047

In [10]:
np.mean( np.array(ut_out_prev))

-0.19

In [15]:
np.array(ut_in)

array([ 0.  , -0.2 , -0.15, -0.13,  0.  , -0.06, -0.06, -0.16, -0.09,
       -0.13])

In [14]:
np.mean( np.array(ut_in) )

-0.098

In [13]:
np.mean( np.array(ut_in_prev) ) 

0.0

In [120]:
w = [0.2, 0.0, 0.8]
sim = simulator(l)
env = sim.simulate_environment()
ads =  ADS(env, accident_prob, inj_fat_in, inj_fat_out, w)


In [121]:
ads.road[0] = np.array([0, 2])

In [122]:
ads.people[0] = np.array([0, 10])

In [12]:
ads.ut_in

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.